# 工作流名称为 Android11-4.19
name: Android11-4.19

# 触发条件配置
on:
    workflow_dispatch:  # 允许手动触发工作流执行

# 定义工作流中的作业
jobs:
    build:
        # 指定运行环境为最新版Ubuntu
        runs-on: ubuntu-latest
        
        steps:
            # 步骤1: 检出代码仓库
            - name: Checkout repository
                uses:actions/checkout@v3

            # 步骤2: 安装必要的依赖
            - name: Install dependencies
                run:|
                    sudo apt update
                    sudo apt-get install -y git build-essential bc libssl-dev libelf-dev flex bison dwarves python3 python3-pip device-tree-compiler lz4 p7zip-full make gcc-aarch64-linux-gnu
                
            # 步骤3: 拉取镜像
            - name: Modify MY_LINUX_VERSION_CODE
                run:|
                    git clone --depth=1 https://github.com/qianxiao1234/Realking_kernel_sm8250.git
                    cd Realking_kernel_sm8250
                    git clone https://github.com/tiann/KernelSU.git
                    cd KernelSU
                    git checkout d6860160e807257a702d6ed9b9cdeae25713bc66
                    cd

            # 步骤4: 构建Android内核
            - name: Build Android Kernel
                continue-on-error:true
                run:|
                    cd Realking_kernel_sm8250
                    ./build_alioth.sh
